name: AdvancedSleep
version: '1.0.0'
main: org.superminers.advancedSleep.AdvancedSleep
api-version: "1.16"
authors: [EthanAxe]
description: 高级睡眠插件，支持单人睡觉、比例睡觉、GUI设置和时间加速
commands:
  sleep:
    description: 打开睡眠设置GUI
    usage: /sleep [toggle|percentage|acceleration|speed|delay|reload|help]
    permission: advancedsleep.use
permissions:
  advancedsleep.use:
    description: 允许使用睡眠命令
    default: true
  advancedsleep.admin:
    description: 允许修改睡眠设置
    default: op